### ISSUE TITLE
Does not run on 1.9 ERL

### ISSUE THREAD

**Issue by Kosmatik** [SeanMollet/1x_prox#1]
#2 This doesn't seem to run on ERL while the original script does. However I would prefer to use yours as it should pull a new dhcp address instead of me having to set a static ip.

root@ubnt:/config/1x_prox# ./1x_prox eth1 eth2
Configuring proxy between:
Wan:            eth1
Wan vlan:       eth1.0
Lan:            eth2
binding ONT/wan to if eth1... bind ok, if eth1 idx: 3
binding RG/int to if eth2... bind ok, if eth2 idx: 4
select() returned error: Invalid argument
select(): Invalid argument
wan_sock: no data: Bad file descriptor
binding ONT/wan to if eth1... bind ok, if eth1 idx: 3
binding RG/int to if eth2... bind ok, if eth2 idx: 4
select() returned error: Invalid argument
select(): Invalid argument
wan_sock: no data: Bad file descriptor
binding ONT/wan to if eth1... bind ok, if eth1 idx: 3
binding RG/int to if eth2... bind ok, if eth2 idx: 4
select() returned error: Invalid argument
select(): Invalid argument
wan_sock: no data: Bad file descriptor
binding ONT/wan to if eth1... bind ok, if eth1 idx: 3
binding RG/int to if eth2... bind ok, if eth2 idx: 4
select() returned error: Invalid argument
select(): Invalid argument
wan_sock: no data: Bad file descriptor
binding ONT/wan to if eth1... bind ok, if eth1 idx: 3
binding RG/int to if eth2... bind ok, if eth2 idx: 4
select() returned error: Invalid argument
select(): Invalid argument
wan_sock: no data: Bad file descriptor
binding ONT/wan to if eth1... bind ok, if eth1 idx: 3
binding RG/int to if eth2... bind ok, if eth2 idx: 4
select() returned error: Invalid argument
select(): Invalid argument

**Comment by SeanMollet** [comment]
Kormatic fixed it.
