### ISSUE TITLE
Request: 1x_prox.c compiled binary

### ISSUE THREAD

**Issue by noc007** [SeanMollet/1x_prox#3]
Would it be possible to compile the latest commit to 1x_prox.c and make it available? I have an ER-X on 1.10 and haven't been able to compile directly on the device with apt-get saying I've got broken packages.

**Comment by SeanMollet** [comment]
I've stopped using this and moved to the re-write that was done in Python. https://github.com/jaysoffian/eap_proxy
It works great and is easier to set up.
